---
title: "Informative Title"
author: "Ava Cascario, Sydney Holt, and Kacie Rohn"
date: "Dec. 3, 2024"
date-modified: now
format: 
  pdf: 
    toc: false
    number-sections: false
    number-depth: 5
    fig-align: center
    cap-location: top
    geometry: 
      - top=1in
      - left=1in
      - right=1in
      - bottom=1in
    colorlinks: true
execute: 
  echo: false
  warning: false
---

```{r codeAppend, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```

```{r}
#| label: load_packages
# Load Packages
library(ggplot2)
library(dplyr)
```

# **Research Topic: Field of Study vs Occupation**

# **Research Questions**

# **Provenance Of Our Data**

# **FAIR and CARE Principles**

```{r}
#| label: load_data
# Load Data
shopping_trends_raw <- read.csv(
  file = "shopping_trends.csv", 
  header = TRUE, 
  sep = ","
)
```

```{r}
#| label: summarize_data
# Summarize Data
item_purchased_data <- shopping_trends_raw %>%
  group_by(
    Location, 
    Season, 
    Item.Purchased
  ) %>%
  summarize(
    Item.Count = n(), 
    .groups = "drop"
  )
```

```{r}
#| label: group_states_by_region
# Group States by Region
state_to_region <- c(
  "Maine" = "Northeast", 
  "New Hampshire" = "Northeast", 
  "Vermont" = "Northeast", 
  "Massachusetts" = "Northeast",
  "Rhode Island" = "Northeast",
  "Connecticut" = "Northeast",
  "New York" = "Northeast",
  "New Jersey" = "Northeast",
  "Pennsylvania" = "Northeast",
  "Delaware" = "South",
  "Maryland" = "South",
  "Virginia" = "South",
  "North Carolina" = "South",
  "South Carolina" = "South",
  "Georgia" = "South",
  "Florida" = "South",
  "West Virginia" = "South",
  "Kentucky" = "South",
  "Tennessee" = "South",
  "Alabama" = "South",
  "Mississippi" = "South",
  "Arkansas" = "South",
  "Louisiana" = "South",
  "Oklahoma" = "South",
  "Texas" = "South",
  "Indiana" = "Midwest", 
  "Illinois" = "Midwest",
  "Michigan" = "Midwest",
  "Ohio" = "Midwest",
  "Wisconsin" = "Midwest",
  "Missouri" = "Midwest",
  "Iowa" = "Midwest",
  "Minnesota" = "Midwest",
  "North Dakota" = "Midwest",
  "South Dakota" = "Midwest",
  "Nebraska" = "Midwest",
  "Kansas" = "Midwest",
  "Montana" = "West",
  "Wyoming" = "West",
  "Colorado" = "West",
  "Idaho" = "West",
  "Nevada" = "West",
  "Utah" = "West",
  "Arizona" = "West",
  "New Mexico" = "West",
  "Washington" = "West",
  "Oregon" = "West",
  "California" = "West",
  "Alaska" = "West",
  "Hawaii" = "West"
)
```

```{r}
#| label: new_region_column
# New Column Added for Region
item_purchased_data <- item_purchased_data %>%
  mutate(
    Region = state_to_region[Location]
  )
```

```{r}
#| label: filter_by_season
# Filter Data by Season
spring_data <- item_purchased_data %>%
  filter(Season == "Spring")

summer_data <- item_purchased_data %>%
  filter(Season == "Summer")

fall_data <- item_purchased_data %>%
  filter(Season == "Fall")

winter_data <- item_purchased_data %>%
  filter(Season == "Winter")
```


```{r}
#| label: visualize_items_by_region_and_season
# Visualization of Data by Region Summarized by Season
plot_items_by_season <- function(
    item_purchased_data, 
    season_name
    ) {
ggplot(
  item_purchased_data, 
  aes(
    x = Item.Purchased,
    y = Item.Count, 
    fill = Region
  )
) +
  geom_bar(
    stat = "Identity", 
    position = position_dodge(width = 0.8), 
    width = 0.8
  ) +
  scale_x_discrete(
    expand = expansion(add = c(0.5, 0.5))
  ) +
  labs(
    title = paste(
      "Items Bought by Region", 
      season_name
    ),  
    x = "Item", 
    y = "Number of Items Bought", 
    fill = "Region"
  ) +
  scale_fill_manual(
    values = c(
      "Northeast" = "#779ECB", 
      "South" = "#486856", 
      "Midwest" = "#FFD580", 
      "West" = "#FF7F7F"
    )
  ) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(
      angle = 45, 
      hjust = 1, 
      size = 10
    ), 
    legend.position = "top", 
    plot.title = element_text(
      size = 18, 
      hjust = 0.5, 
      face = "bold"
    ), 
    plot.margin = margin(20, 20, 20, 20)
  )
}
```

```{r}
#| label: create_each_plot

spring_plot <- plot_items_by_season(spring_data, "Spring")
summer_plot <- plot_items_by_season(summer_data, "Summer")
fall_plot <- plot_items_by_season(fall_data, "Fall")
winter_plot <- plot_items_by_season(winter_data, "Winter")

print(spring_plot)
print(summer_plot)
print(fall_plot)
print(winter_plot)

```

